language: java
sudo: false
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
script:
    mvn clean install -DskipTest;
    cd hadoop-ssm-project;
    mvn test
